# Chapter-9 Standard Libraries
This notebook contains the sample source code explained in the book *Hands-On Julia Programming, Sambit Kumar Dash, 2021, bpb Publications. All Rights Reserved*.

In [123]:
using Pkg
pkg"activate ."
pkg"instantiate"

  Activating project at `C:\Users\WoU_AI_ML\Desktop\vaishnavi\Hands-on-Julia-Programming\Chapter 09`

Step: 13


## 9.1 Introduction

There are various functions and methods that are part of Julia already. A developer needs to use them directly rather than having to code for them. This chapter is a bird's eyeview of such methods. 

### Modules

Namespaces where a method or a type reside. Using a method or type outside the module may require explicit qualification. 

In [124]:
module m1
    function f()
        println("Defined as m1.f")
    end
    function g()
        println("Defined as m1.g")
    end
    function h()
        println("Defined as m1.h")
    end
    export f
end

module m2
    function f()
        println("Defined as m2.f")
    end
    function g()
        println("Defined as m2.g")
    end
    export g
end

Main.m2

In [125]:
names(m1)

2-element Vector{Symbol}:
 :f
 :m1

In [126]:
names(m2)

2-element Vector{Symbol}:
 :g
 :m2

In [127]:
f()

Defined as m1.f


In [128]:
m1.f()

Defined as m1.f


In [129]:
m2.f()

Defined as m2.f


In [130]:
using .m1

In [131]:
f()

Defined as m1.f


In [132]:
g()

Defined as m2.g


In [133]:
using Main.m2

In [134]:
g()

Defined as m2.g


In [135]:
using .m1: g

In [136]:
g()

Defined as m2.g


In [137]:
using .m1: h

In [138]:
h()

Defined as m1.h


## 9.2 Standard Modules

`Core`, `Base` and `Main` the bare minimum modules of a Julia shell. `m1` and `m2` here are submodules of `Main`.

In [139]:
varinfo()

| name    |       size | summary                     |
|:------- | ----------:|:--------------------------- |
| A       |  136 bytes | 3×4 Matrix{Float64}         |
| A2      |    0 bytes | Nothing                     |
| Base    |            | Module                      |
| Core    |            | Module                      |
| Main    |            | Module                      |
| c       | 64.289 KiB | TCPSocket                   |
| d       |    8 bytes | Date                        |
| data    |  1.602 KiB | 100×2 Matrix{Float64}       |
| fd      |  359 bytes | IOStream                    |
| fs      |  146 bytes | Base.Filesystem.StatStruct  |
| header  |  1.180 KiB | 1×2 Matrix{AbstractString}  |
| io      |   88 bytes | IOBuffer                    |
| m1      |  5.623 KiB | Module                      |
| m2      |  4.770 KiB | Module                      |
| nc      |    8 bytes | Int64                       |
| nr      |    8 bytes | Int64                       |
| old_dir |   82 bytes | 74-codeunit String          |
| p       |   96 bytes | Dates.CompoundPeriod        |
| str     |   38 bytes | 30-codeunit String          |
| t       |    8 bytes | DateTime                    |
| x       |  840 bytes | 100-element Vector{Int64}   |
| y       |  840 bytes | 100-element Vector{Float64} |


In [140]:
x = 1

1

In [141]:
varinfo()

| name    |       size | summary                     |
|:------- | ----------:|:--------------------------- |
| A       |  136 bytes | 3×4 Matrix{Float64}         |
| A2      |    0 bytes | Nothing                     |
| Base    |            | Module                      |
| Core    |            | Module                      |
| Main    |            | Module                      |
| c       | 64.289 KiB | TCPSocket                   |
| d       |    8 bytes | Date                        |
| data    |  1.602 KiB | 100×2 Matrix{Float64}       |
| fd      |  359 bytes | IOStream                    |
| fs      |  146 bytes | Base.Filesystem.StatStruct  |
| header  |  1.180 KiB | 1×2 Matrix{AbstractString}  |
| io      |   88 bytes | IOBuffer                    |
| m1      |  5.623 KiB | Module                      |
| m2      |  4.770 KiB | Module                      |
| nc      |    8 bytes | Int64                       |
| nr      |    8 bytes | Int64                       |
| old_dir |   82 bytes | 74-codeunit String          |
| p       |   96 bytes | Dates.CompoundPeriod        |
| str     |   38 bytes | 30-codeunit String          |
| t       |    8 bytes | DateTime                    |
| x       |    8 bytes | Int64                       |
| y       |  840 bytes | 100-element Vector{Float64} |


## 9.3 System

The submodule that interacts with the operating system. System command execution being one of them. 

In [142]:
run(`cmd /c dir`)

 Volume in drive C is OS
 Volume Serial Number is 3E32-AD10

 Directory of C:\Users\WoU_AI_ML\Desktop\vaishnavi\Hands-on-Julia-Programming\Chapter 09

01-10-2022  21:12    <DIR>          .
01-10-2022  21:08    <DIR>          ..
01-10-2022  21:11    <DIR>          .ipynb_checkpoints
01-10-2022  21:08            68,389 Chapter-9 Standard Libraries.ipynb
01-10-2022  21:12         6,949,901 julia-1.5.3.tar.gz
01-10-2022  21:11             5,798 Manifest.toml
01-10-2022  21:08                57 Project.toml
               4 File(s)      7,024,145 bytes
               3 Dir(s)  152,117,178,368 bytes free


Process(`cmd /c dir`, ProcessExited(0))

In [143]:
Sys.isunix(), Sys.iswindows()

(false, true)

## 9.4 Filesystem

File organization and manipulation (not read and write). 

In [144]:
old_dir = pwd()

"C:\\Users\\WoU_AI_ML\\Desktop\\vaishnavi\\Hands-on-Julia-Programming\\Chapter 09"

In [145]:
cd("..")

In [146]:
pwd()

"C:\\Users\\WoU_AI_ML\\Desktop\\vaishnavi\\Hands-on-Julia-Programming"

In [147]:
cd(old_dir)

In [148]:
pwd()

"C:\\Users\\WoU_AI_ML\\Desktop\\vaishnavi\\Hands-on-Julia-Programming\\Chapter 09"

In [149]:
cd(".."); pwd()

"C:\\Users\\WoU_AI_ML\\Desktop\\vaishnavi\\Hands-on-Julia-Programming"

In [150]:
readdir()  #Same as readdir(pwd())

20-element Vector{String}:
 ".DS_Store"
 ".git"
 "Chapter 02"
 "Chapter 03"
 "Chapter 04"
 "Chapter 05"
 "Chapter 06"
 "Chapter 07"
 "Chapter 08"
 "Chapter 09"
 "Chapter 10"
 "Chapter 11"
 "Chapter 12"
 "Chapter 13"
 "Chapter 14"
 "Chapter 15"
 "Chapter 16"
 "Chapter 17"
 "LICENSE"
 "README.md"

In [151]:
for (root, dirs, files) in walkdir("Chapter-09")
    println("Directories in $root")
    for dir in dirs
        println(joinpath(root, dir)) # path to directories
    end
    println("Files in $root")
    for file in files
        println(joinpath(root, file)) # path to files
    end
end

In [152]:
cd(old_dir); pwd()

"C:\\Users\\WoU_AI_ML\\Desktop\\vaishnavi\\Hands-on-Julia-Programming\\Chapter 09"

In [153]:
fs = stat("Chapter-9 Standard Libraries.ipynb")

StatStruct for "Chapter-9 Standard Libraries.ipynb"
   size: 68389 bytes
 device: 1043508496
  inode: 1768387
   mode: 0o100666 (-rw-rw-rw-)
  nlink: 1
    uid: 0
    gid: 0
   rdev: 0
  blksz: 4096
 blocks: 136
  mtime:  (4 minutes ago)
  ctime:  (4 minutes ago)

## 9.5 Parallel Programming

Execution of programs in tandem in various execution environments, yet be able to obtain meaningful and synchronized results. Performance and resource utilization are two major outcomes of this kind of programming. 

### Asynchronous Programming

Breaking the code into small chunks of executable pieces that can be executed in parallel. Depending on the kind of processing permitted by the hardware and OS, these may run in one execution thread or multiple.

#### Tasks

In [154]:
t = Task() do 
    sleep(10)
    println("done")
end

Task (runnable) @0x000000000c062100

In [155]:
schedule(t)

Task (runnable) @0x000000000c062100

In [156]:
t = Task() do 
    sleep(10)
    println("done")
end

Task (runnable) @0x000000000c062ca0

In [157]:
schedule(t); wait(t)

Step: 14
Step: 15
Step: 16
Step: 17
Step: 18
Step: 19
Step: 20
Step: 21
Step: 22
Step: 23
done
done


In [158]:
t = @task begin
    sleep(5)
    println("done")
end

Task (runnable) @0x000000000c062e90

In [159]:
@sync  begin
    sleep(5)
    println("done")
end

Step: 24
Step: 25
Step: 26
Step: 27
Step: 28
done


#### Channels

In [160]:
c = Channel(8)

Channel{Any}(8) (empty)

In [161]:
c = Channel{Int}(4)

Channel{Int64}(4) (empty)

In [162]:
@async begin
    for i = 1:100
        println("Adding $i to channel")
        put!(c, i)
    end
end

@async begin
    for i = 1:100
        v = take!(c)
        println("Removing value: $v")
    end
end

Task (runnable) @0x000000000c063270

Adding 1 to channel


In [163]:
close(c)

Adding 2 to channel
Adding 3 to channel
Removing value: 1


### Multithreading

Julia can be made to run on a multiple threads mode. In such a conditions the tasks can be parallelized on these threads. Synchronization objects can be used across the executing threads. 

In [164]:
Threads.nthreads()

Removing value: 2


1

In [165]:
Threads.@spawn for i=1:100
    sleep(1)
    println("Step: $i")
end

Task (runnable) @0x000000000c9d64e0

### Distributed Computing

This is cluster computing infrastrcuture, where a cluster can be configured across Julia processes in the same machine or in another machine. These independent processes can execute independently yet be able to share data, pass messages and communicate over a shared channel. 

## 9.6 IO and Network

Julia accesses input and output devices as streams. The network devices are also interfaced like sockets. IO is an important stream based interface to understand. 

### Default Stream

`stdin`, `stdout` and `stderr` are the standard streams for input, output and error in most processes. `stdin` integration with Jupyter is limited. All those samples may best be reviewed in a REPL console. 

In [166]:
write(stdout, "Hello World")

Hello World

11

In [167]:
write(stdout, "\u2200 x \u2203 y")

∀ x ∃ y

11

### Text I/O

### Binary I/O

### File I/O

Files are also accessed as `IO` streams for both read and write operations. However, the `IO` streams are obtained by `open` call. Any open stream must be closed with a `close` function call. 

In [168]:
write("hello.txt", "Hello World")

11

In [169]:
fd = open("hello.txt", "r");
data = read(fd);

In [170]:
write(fd, "This is second line")

LoadError: ArgumentError: write failed, IOStream is not writeable

In [171]:
close(fd)
write(stdout, data)

Hello World

11

In [172]:
open("hello.txt", "r") do fd
    data = read(fd)
    write(stdout, data)
end

Hello World

11

In [173]:
write("hello.txt", "Hello World");
data = read("hello.txt");
write(stdout, data);

Hello World

Files are opened for `read` or `write`. A file opened for reading cannot be written into.  

In [174]:
open("hello.txt", "r") do fd
    while !eof(fd)
        b = read(fd, 1)
        write(stdout, b)
    end
end
rm("hello.txt")

Hello World

### Delimited Files

Generalized command separated value (CSV) kind of files. Used extensively in spreadsheets. Also interfaced in data science applications as an easier way to share data. 

In [175]:
using DelimitedFiles
x = collect(1:100);
y = Float64.(collect(101:200));
open("values.csv", "w") do f
    println(f, "X,Y")
    writedlm(f, [x y], ',')
end

In [176]:
data, header = readdlm("values.csv", ',', header=true);

In [177]:
size(data, 1)

100

In [178]:
header

1×2 Matrix{AbstractString}:
 "X"  "Y"

In [179]:
rm("values.csv")

### Network 

Just like files are opened with open to obtain the `IO` stream to interface, sockets are equivalent network communication end points to obtain connection streams. However, if you could use download method to provide a URL and download files. 

In [180]:
download("https://github.com/JuliaLang/julia/releases/download/v1.5.3/julia-1.5.3.tar.gz", "julia-1.5.3.tar.gz")

Step: 29
Step: 1
Step: 30
Step: 2
Step: 31
Step: 3
Step: 32
Step: 4
Step: 33
Step: 5
Step: 34
Step: 6


"julia-1.5.3.tar.gz"

In [181]:
using Sockets
@async begin
    server = listen(3000)
    while true
        s = accept(server)
        @async while isopen(s)
            msg = readline(s, keep=true)
            write(s, "Server Response: $msg")
        end  
    end
end

Task (failed) @0x00000000d1c66e90
IOError: listen: address already in use (EADDRINUSE)
Stacktrace:
 [1] uv_error
   @ .\libuv.jl:97 [inlined]
 [2] #listen#13
   @ C:\Users\WoU_AI_ML\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Sockets\src\Sockets.jl:629 [inlined]
 [3] #listen#10
   @ C:\Users\WoU_AI_ML\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Sockets\src\Sockets.jl:622 [inlined]
 [4] #listen#12
   @ C:\Users\WoU_AI_ML\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Sockets\src\Sockets.jl:626 [inlined]
 [5] #listen#11
   @ C:\Users\WoU_AI_ML\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Sockets\src\Sockets.jl:625 [inlined]
 [6] listen
   @ C:\Users\WoU_AI_ML\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Sockets\src\Sockets.jl:625 [inlined]
 [7] macro expansion
   @ .\In[181]:3 [inlined]
 [8] (::var"#51#53")()
   @ Main .\task.jl:484

In [182]:
c = connect(3000)
@async while isopen(c)
    println(stdout, readline(c, keep=true))
end

Task (runnable) @0x00000000d1c67a30

In [183]:
for i = 1:5
    println(c, "Client Msg id: $i")
end

Server Response: Client Msg id: 1

Server Response: Client Msg id: 2


In [184]:
close(c)


Server Response: Client Msg id: 3



### Memory I/O

Strings cannot be manipulated. It may help to create a byte array for `IO` in the memory and use that for text manipulations. In the end the byte array can be converted to a String. 

In [185]:
io = IOBuffer()
println(io, "This is Line 1")
println(io, "This is Line 2")
str = String(take!(io))

"This is Line 1\nThis is Line 2\n"

In [186]:
A = fill(10, (5, 20))
A[2, 3] = 20
open("mmap.bin", "w+") do fd
    write(fd, size(A, 1))
    write(fd, size(A, 2))
    write(fd, A)
end

800

Memory mapping is reverse problem. A file can be mapped to memory and accessed selectively page by page. This way the whole file need not be loaded in the memory. 

In [187]:
using Mmap
fd = open("mmap.bin", "r")
nr = read(fd, Int)
nc = read(fd, Int)
A2 = Mmap.mmap(fd, Matrix{Int}, (nr, nc))
println("A2[1, 1]: ", A2[1, 1], " A2[2, 3]: ", A2[2, 3])
close(fd)

A2[1, 1]: 10 A2[2, 3]: 20


In [188]:
A2 = nothing
GC.gc()
rm("mmap.bin")

## 9.7 Constants

There are many system and Julia related constants. Mathematical constants are also defined in the standard library. 

In [189]:
VERSION

v"1.8.0"

In [190]:
C_NULL

Ptr{Nothing} @0x0000000000000000

In [191]:
Sys.BINDIR

"C:\\Users\\WoU_AI_ML\\AppData\\Local\\Programs\\Julia-1.8.0\\bin"

In [192]:
Sys.CPU_THREADS

20

In [193]:
Sys.WORD_SIZE

64

In [194]:
Sys.KERNEL

:NT

In [195]:
Sys.MACHINE

"x86_64-w64-mingw32"

In [196]:
Sys.ARCH

:x86_64

In [197]:
Sys.ENV

Base.EnvDict with 68 entries:
  "=C:"                            => "C:\\Users\\WoU_AI_ML\\Desktop\\vaishnavi…
  "ALLUSERSPROFILE"                => "C:\\ProgramData"
  "AMOSAPP"                        => "C:\\Users\\WoU_AI_ML\\AppData\\Local\\Am…
  "AMOSDOCS"                       => "C:\\Users\\WoU_AI_ML\\Documents\\AmosDev…
  "AMOSEXAMPLES"                   => "C:\\Users\\WoU_AI_ML\\AppData\\Local\\Am…
  "AMOSLOGS"                       => "C:\\Users\\WoU_AI_ML\\AppData\\Local\\Am…
  "AMOSPLUGINS"                    => "C:\\Users\\WoU_AI_ML\\AppData\\Local\\Am…
  "AMOSPROGRAM"                    => "C:\\Program Files\\IBM\\SPSS\\Amos\\28"
  "AMOSTEMPLATES"                  => "C:\\Users\\WoU_AI_ML\\AppData\\Local\\Am…
  "AMOSTUTORIAL"                   => "C:\\Users\\WoU_AI_ML\\AppData\\Local\\Am…
  "APPDATA"                        => "C:\\Users\\WoU_AI_ML\\AppData\\Roaming"
  "COLUMNS"                        => "80"
  "COMMONPROGRAMFILES"             => "C:\\Program Files\\Common 

In [198]:
MathConstants.pi

π = 3.1415926535897...

In [199]:
MathConstants.e

ℯ = 2.7182818284590...

## 9.8 Notable Modules

Miscellaneous modules of Julia library. 

### Dates

User renderable date and time representations. In the system the date is just a continuously increasing counter from a datum. These functions make meaningful period associations and provide the correct date and time. 

In [200]:
using Dates

In [201]:
now()

2022-10-01T21:12:45.155

In [202]:
DateTime(2020)

2020-01-01T00:00:00

In [203]:
t = DateTime(2020, 10, 31, 01, 02, 03)

2020-10-31T01:02:03

In [204]:
Date(2020)

2020-01-01

In [205]:
d = Date(t)

2020-10-31

In [206]:
DateTime(d)

2020-10-31T00:00:00

In [207]:
t > d

true

In [208]:
DateTime(2020) < now()

true

In [209]:
DateTime(2020) == Date(2020)

true

In [210]:
p = Month(3) + Day(10) + Hour(15)

3 months, 10 days, 15 hours

In [211]:
typeof(p)

Dates.CompoundPeriod

In [212]:
now() + p

2023-01-12T12:12:45.161

In [213]:
Date(now())+ Day(300)

2023-07-28

In [214]:
now() - DateTime(2020)

86821965162 milliseconds

In [215]:
now() - Date(2020)

LoadError: MethodError: no method matching -(::DateTime, ::Date)
Closest candidates are:
  -(::StridedArray{<:Union{Dates.CompoundPeriod, Period}}, ::TimeType) at C:\Users\WoU_AI_ML\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Dates\src\deprecated.jl:26
  -(::TimeType, ::Dates.CompoundPeriod) at C:\Users\WoU_AI_ML\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Dates\src\periods.jl:400
  -(::T, ::T) where T<:TimeType at C:\Users\WoU_AI_ML\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Dates\src\arithmetic.jl:9
  ...

In [216]:
Date(now()) - Date(2020)

1004 days

In [217]:
Year(now())

2022 years

In [218]:
Month(now())

10 months

In [219]:
Day(now())

1 day

In [220]:
Week(now())

39 weeks

In [221]:
year(now())

2022

In [222]:
tonext(today()) do d
    dayofweek(d) == Thursday &&
    dayofweekofmonth(d) == 4 &&
    month(d) == November
end

2022-11-24

### Logging

Long running processes or servers running in Julia need to provide consistent and standard log reporting. This module helps create such reports. 

In [223]:
@debug "This is a debug message $(sum(rand(100)))"

In [224]:
@info "This message is just informational"

┌ Info: This message is just informational
└ @ Main In[224]:1


In [225]:
@warn "This is a warning message"

┌ Warning: This is a warning message
└ @ Main In[225]:1


In [226]:
@error "This is an error message"

┌ Error: This is an error message
└ @ Main In[226]:1


In [227]:
A = ones(3, 4)
@info "A is all ones" A

┌ Info: A is all ones
│   A = [1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0]
└ @ Main In[227]:2


The `Logging` module provides interfaces to implement complete loggers. It also provides the ability to override the global logger with a different local one. 

In [228]:
using Logging

In [229]:
open("file.log", "w") do f
    with_logger(SimpleLogger(f)) do
        @info "This is my simple info log"
        @error "This is an error written to file"
        @warn "This is a warning message"
        @info "Current logger is same as global logger" current_logger() == global_logger()
    end
end
write(stdout, read("file.log"));

┌ Info: This is my simple info log
└ @ Main In[229]:3
┌ Error: This is an error written to file
└ @ Main In[229]:4
┌ Warning: This is a warning message
└ @ Main In[229]:5
┌ Info: Current logger is same as global logger
│   current_logger() == global_logger() = false
└ @ Main In[229]:6


In [230]:
rm("file.log")

In [231]:
@info "Current logger is same as global logger" current_logger() == global_logger()

┌ Info: Current logger is same as global logger
│   current_logger() == global_logger() = true
└ @ Main In[231]:1


### Statistics

This module provides simple functions for central tendencies like mean, median and standard deviations etc. Functions for correlations and covariances are also provided. However, the treatment of statistics in thi module are highly rudimentary. 

In [232]:
using Statistics

In [233]:
mean(1:10)

5.5

In [234]:
median(1:10)

5.5

In [235]:
std(1:10)

3.0276503540974917

In [236]:
var(1:10)

9.166666666666666

In [237]:
cor(1:10, rand(10))

0.11989198544387174

In [238]:
cor(1:10, 11:20)

1.0

In [239]:
cov(1:10, rand(10))

0.14213825169013614

### Random Numbers

Provides methods for random number generation and other permutation and combination functions. 

In [240]:
using Random

In [241]:
rand(Int, 2)

2-element Vector{Int64}:
 -5234248151739929841
  2044370689589140896

In [242]:
rand(2, 3)

2×3 Matrix{Float64}:
 0.256652  0.166058  0.0720184
 0.946681  0.316257  0.224636

In [243]:
rand!(zeros(2, 3))

2×3 Matrix{Float64}:
 0.275296  0.318992  0.71478
 0.792983  0.306974  0.488793

In [245]:
rand(1:4, (2, 3))

2×3 Matrix{Int64}:
 4  1  1
 3  3  1

## 9.9 Conclusion

## Exercises